/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthLoginRateLimits {
  blocked_until: Timestamp;
  failed_count: Generated<number>;
  first_attempt_at: Timestamp;
  rate_key: string;
  updated_at: Generated<Timestamp>;
}

export interface Branches {
  code: Generated<string>;
  created_at: Generated<Timestamp | null>;
  name: string;
  state: boolean;
  users: string[];
}

export interface Brands {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DriveFiles {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  mime_type: string | null;
  name: string;
  parent_code: string | null;
  scope: Generated<string>;
  size: Generated<Int8>;
  storage_path: string | null;
  tag: string | null;
  type: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_code: string;
}

export interface DriveLinks {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  file_code: string;
  is_primary: Generated<boolean>;
  linked_by_user_code: string;
  position: Generated<number>;
  product_code: string;
}

export interface InventoryBalances {
  available: Generated<number | null>;
  branch_code: string;
  created_at: Generated<Timestamp>;
  emergency_point: Generated<number>;
  inbound: Generated<number>;
  last_movement_at: Timestamp | null;
  on_hand: Generated<number>;
  product_code: string;
  reorder_point: Generated<number>;
  reserved: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface InventoryCustomerFeed {
  code: string | null;
  created_at: Timestamp | null;
  full_name: string | null;
  note: string | null;
  phone: string | null;
  updated_at: Timestamp | null;
}

export interface InventoryCustomers {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  full_name: string;
  note: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface InventoryMovementFeed {
  branch_code: string | null;
  branch_name: string | null;
  code: string | null;
  created_at: Timestamp | null;
  direction: string | null;
  note: string | null;
  occurred_at: Timestamp | null;
  product_code: string | null;
  product_name: string | null;
  product_sku: string | null;
  purchase_code: string | null;
  quantity: number | null;
  reason: string | null;
  sale_code: string | null;
  updated_at: Timestamp | null;
  user_code: string | null;
}

export interface InventoryMovements {
  branch_code: string;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  direction: string;
  note: string | null;
  occurred_at: Generated<Timestamp>;
  product_code: string;
  purchase_code: string | null;
  quantity: number;
  reason: string;
  sale_code: string | null;
  updated_at: Generated<Timestamp>;
  user_code: string;
}

export interface InventoryOverview {
	available: number | null;
	awaiting_first_stock: boolean | null;
	branch_code: string | null;
	branch_name: string | null;
	category_code: string | null;
	category_name: string | null;
	cost_price: Numeric | null;
	created_at: Timestamp | null;
	emergency_point: number | null;
	inbound: number | null;
	last_movement_at: Timestamp | null;
	on_hand: number | null;
	price: Numeric | null;
	product_code: string | null;
	product_is_active: boolean | null;
  product_name: string | null;
  reorder_point: number | null;
  reserved: number | null;
  sku: string | null;
  stock_health_pct: number | null;
  stock_state: string | null;
  updated_at: Timestamp | null;
}

export interface InventoryPurchaseFeed {
  branch_code: string | null;
  branch_name: string | null;
  can_refund: boolean | null;
  code: string | null;
  created_at: Timestamp | null;
  entry_type: string | null;
  item_count: number | null;
  items: Json | null;
  note: string | null;
  ordered_at: Timestamp | null;
  origin: string | null;
  primary_product_code: string | null;
  primary_product_name: string | null;
  primary_product_sku: string | null;
  products_summary: string | null;
  received_at: Timestamp | null;
  refunded_at: Timestamp | null;
  state: string | null;
  total_amount: Numeric | null;
  total_quantity: number | null;
  tracking_number: string | null;
  updated_at: Timestamp | null;
  user_code: string | null;
}

export interface InventorySaleFeed {
  branch_code: string | null;
  branch_name: string | null;
  code: string | null;
  created_at: Timestamp | null;
  customer_code: string | null;
  customer_full_name: string | null;
  customer_name: string | null;
  customer_phone: string | null;
  delivery_address: string | null;
  fulfillment_type: string | null;
  item_count: number | null;
  items: Json | null;
  note: string | null;
  order_reference: string | null;
  primary_product_code: string | null;
  primary_product_name: string | null;
  primary_product_sku: string | null;
  products_summary: string | null;
  profit_amount: Numeric | null;
  sale_channel: string | null;
  shipping_state: string | null;
  sold_at: Timestamp | null;
  total_amount: Numeric | null;
  total_quantity: number | null;
  updated_at: Timestamp | null;
  user_code: string | null;
  void_note: string | null;
  voided_at: Timestamp | null;
  voided_by_name: string | null;
  voided_by_user_code: string | null;
}

export interface Migrations {
  batch: number;
  executed_at: Generated<Timestamp>;
  id: string;
  name: string;
}

export interface Permissions {
  action: string;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  user_code: string;
}

export interface Products {
  brand_code: string;
  category_code: string;
  code: Generated<string>;
  cost_price: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  description: string | null;
  is_active: Generated<boolean>;
  name: string;
  price: Numeric;
  sku: string | null;
  updated_at: Generated<Timestamp>;
  user_code: string;
}

export interface ProductsOverview {
  brand_code: string | null;
  brand_name: string | null;
  category_code: string | null;
  category_name: string | null;
  code: string | null;
  cost_price: Numeric | null;
  created_at: Timestamp | null;
  description: string | null;
  has_images: boolean | null;
  images: Json | null;
  images_count: number | null;
  is_active: boolean | null;
  name: string | null;
  price: Numeric | null;
  primary_image_url: string | null;
  sku: string | null;
  updated_at: Timestamp | null;
}

export interface PurchaseItems {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  product_code: string;
  purchase_code: string;
  quantity: number;
  total_amount: Generated<Numeric | null>;
  unit_cost: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface Purchases {
  branch_code: string;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  entry_type: Generated<string>;
  note: string | null;
  ordered_at: Generated<Timestamp>;
  origin: string;
  received_at: Timestamp | null;
  refunded_at: Timestamp | null;
  state: Generated<string>;
  tracking_number: string | null;
  updated_at: Generated<Timestamp>;
  user_code: string;
}

export interface SaleItems {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  product_code: string;
  quantity: number;
  sale_code: string;
  total_amount: Generated<Numeric | null>;
  unit_cost: Generated<Numeric>;
  unit_price: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface Sales {
  branch_code: string;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  customer_code: string | null;
  customer_name: string;
  customer_phone: string | null;
  delivery_address: string | null;
  fulfillment_type: Generated<string>;
  note: string | null;
  order_reference: string | null;
  sale_channel: Generated<string>;
  shipping_state: Generated<string>;
  sold_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_code: string;
  void_note: string | null;
  voided_at: Timestamp | null;
  voided_by_user_code: string | null;
}

export interface Users {
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  email: string;
  is_super_admin: Generated<boolean>;
  last_login: Timestamp | null;
  last_name: string | null;
  name: string | null;
  password_hash: string;
  photo_url: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  auth_login_rate_limits: AuthLoginRateLimits;
  branches: Branches;
  brands: Brands;
  categories: Categories;
  drive_files: DriveFiles;
  drive_links: DriveLinks;
  inventory_balances: InventoryBalances;
  inventory_customer_feed: InventoryCustomerFeed;
  inventory_customers: InventoryCustomers;
  inventory_movement_feed: InventoryMovementFeed;
  inventory_movements: InventoryMovements;
  inventory_overview: InventoryOverview;
  inventory_purchase_feed: InventoryPurchaseFeed;
  inventory_sale_feed: InventorySaleFeed;
  migrations: Migrations;
  permissions: Permissions;
  products: Products;
  products_overview: ProductsOverview;
  purchase_items: PurchaseItems;
  purchases: Purchases;
  sale_items: SaleItems;
  sales: Sales;
  users: Users;
}
